[package]
name = "Advent of Code 2016"
version = "0.1.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
description = "Solutions to the Advent of Code 2016 puzzles"

[dependencies]

[[bin]]
name = "day01"
